# Generated by Django 2.2.4 on 2022-03-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_detail',
            name='status',
            field=models.CharField(choices=[('', 'Select'), ('Activated', 'Activate'), ('Deactivated', 'Deactivate')], max_length=200, null=True),
        ),
    ]
