# Generated by Django 2.2.4 on 2022-03-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_detail_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_Detail',
            new_name='Cloud_User',
        ),
    ]
