# Generated by Django 2.2.4 on 2022-03-06 08:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220306_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='File Name')),
                ('file', models.FileField(null=True, upload_to='documents/', verbose_name='File')),
                ('notes', models.TextField(max_length=2000, verbose_name='Notes')),
                ('upoaded_date', models.DateField(default=datetime.datetime(2022, 3, 6, 8, 22, 34, 412794, tzinfo=utc), verbose_name='Uploaded Date')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cloud_User')),
            ],
        ),
    ]
