# Generated by Django 2.2.4 on 2022-03-06 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='upoaded_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 6, 15, 45, 20, 310112, tzinfo=utc), verbose_name='Uploaded Date'),
        ),
    ]
