# Generated by Django 2.2.4 on 2022-03-06 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220306_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='upoaded_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 6, 19, 27, 33, 353534, tzinfo=utc), verbose_name='Uploaded Date'),
        ),
    ]
