# Generated by Django 2.2.4 on 2022-03-06 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220307_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='private_key',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Private Key'),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='public_key',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='upload_file',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='upoaded_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 6, 19, 38, 7, 907197, tzinfo=utc), verbose_name='Uploaded Date'),
        ),
    ]
